name: Publish posts scheduled for today

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    # Run every day at 23:30 UTC or manually run
    - cron: "30 23 * * *"
  workflow_dispatch:

jobs:
  publish_scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get the date for today
        id: date
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Check for scheduled posts and move to posts
        run: |
          echo "Today is $TODAY"
          if [ -d "_scheduled" ]; then
            shopt -s nullglob
            for file in _scheduled/${TODAY}-*.md; do
              echo "Found scheduled: $file"
              mv "$file" "_posts/"
              echo "Moved $file to _posts/"
            done
          else
            echo "_scheduled directory does not exist. Skipping."
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if [ -d "_posts" ]; then
            git add _posts/
          fi
          if [ -d "_scheduled" ]; then
            git add _scheduled/
          fi
          git commit -m "Posted Scheduled Drafts on $TODAY" || echo "No changes to commit"
          git push
